/**
 * One-shot local dev setup:
 *   1. Starts Postgres (5433) + Redis (6380) via docker-compose.dev.yml
 *   2. Creates apps/backend/.env with required vars if missing
 *   3. Runs migrations on the dev DB (lifty) and the test DB (lifty_test)
 *   4. Seeds districts
 *
 * Run from the repo root: bun run setup
 * Idempotent — safe to re-run whenever.
 */
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

const BACKEND_DIR = join(import.meta.dir, '..');
const REPO_ROOT = join(BACKEND_DIR, '..', '..');
const MIGRATIONS = join(BACKEND_DIR, 'src', 'shared', 'db', 'migrations');
const PG = 'postgresql://lifty:lifty@localhost:5433';

function run(cmd: string[], cwd: string) {
  const proc = Bun.spawnSync(cmd, { cwd, stdout: 'inherit', stderr: 'inherit' });
  if (proc.exitCode !== 0) {
    console.error(`❌ Command failed: ${cmd.join(' ')}`);
    process.exit(proc.exitCode ?? 1);
  }
}

// 1. Infra
console.log('🐳 Starting dev infra (postgres:5433, redis:6380)...');
run(['docker', 'compose', '-f', 'docker-compose.dev.yml', 'up', '-d', '--wait'], REPO_ROOT);

// 2. Pick a free port for the backend (3000 may belong to another project)
function isPortFree(port: number): boolean {
  try {
    const srv = Bun.serve({ port, fetch: () => new Response('') });
    srv.stop(true);
    return true;
  } catch {
    return false;
  }
}
let apiPort = 3000;
while (!isPortFree(apiPort) && apiPort < 3020) apiPort++;
if (apiPort !== 3000) console.log(`⚠️  Port 3000 is taken — backend will use ${apiPort}`);

// 3. Backend .env
const envPath = join(BACKEND_DIR, '.env');
if (!existsSync(envPath)) {
  const secret = crypto.randomUUID().replace(/-/g, '') + crypto.randomUUID().replace(/-/g, '');
  await Bun.write(
    envPath,
    [
      '# Generated by `bun run setup`. DATABASE_URL points at the',
      '# docker-compose.dev.yml Postgres (5433/lifty).',
      '# WARNING: never point DATABASE_URL at a DB you care about and then',
      '# run tests — tests truncate every table.',
      `PORT=${apiPort}`,
      `DATABASE_URL=${PG}/lifty`,
      'REDIS_URL=redis://localhost:6380',
      'SUPABASE_URL=',
      'SUPABASE_PUBLISHABLE_KEY=sb_publishable_...',
      'SUPABASE_SECRET_KEY=sb_secret_...',
      '',
    ].join('\n'),
  );
  console.log('🔑 Created apps/backend/.env');
} else {
  const current = await Bun.file(envPath).text();
  const m = current.match(/^PORT=(\d+)$/m);
  if (m) apiPort = Number(m[1]);
  if (!/^DATABASE_URL=/m.test(current)) {
    await Bun.write(envPath, `${current.trimEnd()}\nDATABASE_URL=${PG}/lifty\n`);
    console.log('🔑 apps/backend/.env: added missing DATABASE_URL (dev Postgres)');
  } else {
    console.log('🔑 apps/backend/.env already exists — leaving it untouched');
  }
}

// Keep the mobile app pointed at the same port (host is auto-detected).
const mobileEnvPath = join(REPO_ROOT, 'apps', 'mobile', '.env');
const mobileEnv = existsSync(mobileEnvPath) ? await Bun.file(mobileEnvPath).text() : '';
if (!mobileEnv.includes('EXPO_PUBLIC_API_PORT')) {
  await Bun.write(mobileEnvPath, `${mobileEnv}EXPO_PUBLIC_API_PORT=${apiPort}\n`);
}

// 4. Migrations on both databases
for (const dbName of ['lifty', 'lifty_test']) {
  console.log(`📦 Migrating ${dbName}...`);
  const pool = new Pool({ connectionString: `${PG}/${dbName}` });
  await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS });
  await pool.end();
}

// 5. Seed (idempotent — skips if districts already exist)
run(['bun', 'run', 'db:seed'], BACKEND_DIR);

console.log(`
✅ Dev environment ready.

  bun run dev        # start backend (:${apiPort}) + expo
  bun run test       # backend test suite (uses lifty_test)

  Postgres : ${PG}/lifty
  Swagger  : http://localhost:${apiPort}/docs
`);
